export const SUPPLIER = {
    ACCOUNT_NUMBER: 'account_number',
    COMPANY_NAME: 'company_name',
    ADDRESS1: 'address1',
    ADDRESS2: 'address2',
    CITY: 'city',
    STATE: 'state',
    POSTAL_CODE: 'postal_code',
    COUNTRY: 'country',
    TAX_TYPE: 'tax_type',
    PAYMENT_TERMS: 'payment_terms',
    PAYMENT_METHOD: 'payment_method',
    PHONE: 'phone',
    PHONE_TOLL_FREE: 'phone_toll_free',
    FAX: 'fax',
    CONTACT_NAME: 'contact_name',
    CONTACT_EMAIL: 'contact_email',
    WEBSITE: 'website',
    ORDER_FROM_WEBSITE: 'order_from_website',
    USERNAME: 'username',
    SUPPLIER_NOTES: 'supplier_notes',
    PO_NOTES: 'po_notes',
};
